import "../globals.css";

export const metadata = {
	title: "Admin",
	description: "Generated by Next.js",
	icons: {
		icon: [
			{
				url: "/logo1.png",
				href: "/logo1.png",
			},
		],
	},
};
import { Toaster } from "sonner";
import { NextAuthProvider } from "@/components/session-provider";
import ReactQueryProvider from "@/lib/react-query";
import { NavbarAd } from "@/components/Navbar";

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Toaster richColors />
				<NextAuthProvider>
					<NavbarAd />
					<ReactQueryProvider>{children}</ReactQueryProvider>
				</NextAuthProvider>
			</body>
		</html>
	);
}
