import { ThemeProvider } from "@/components/theme-provider";
import "../globals.css";

export const metadata = {
	title: "Admin",
	description: "Generated by Next.js",
	icons: {
		icon: [
			{
				url: "/logo.png",
				href: "/logo.png",
			},
		],
	},
};
import { Toaster } from "sonner";
import { NextAuthProvider } from "@/components/session-provider";
import { BackgroundBeams } from "@/components/ui/background-beams";

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Toaster richColors />
					<NextAuthProvider>
						<BackgroundBeams />
						{children}
					</NextAuthProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
